### ISSUE TITLE
Cannot find module 

### ISSUE THREAD

**Issue by lauborges** [totaljs/superadmin#3]
$ bash /www/superadmin/run.sh
> module.js:340
    throw err;
    ^

Error: Cannot find module '/root/release.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
    at node.js:974:3

**Comment by petersirka** [comment]
Hi @lauborges,
we have to fix it, but this works:

```bash
$ cd /www/superadmin/
$ bash run.sh
```

Thanks!

**Comment by molda** [comment]
Fixed
